version: '3.9'
services:
  # web:
  #   build:
  #     context: .
  #     target: web
  #   command: bundle exec rails server -p 3000 -b '0.0.0.0'
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #     - redis
      # - sidekiq
      # - selenium

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gala
      POSTGRES_PASSWORD: alpine
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: web
  #   image: myapp_sidekiq
  #   command: bundle exec sidekiq
  #   depends_on:
  #     - db
  #     - redis

  # selenium:
  #   image: selenium/standalone-chrome:latest
  #   ports:
  #     - '4444:4444'

  # webpacker:
  #   build:
  #     context: .
  #     target: web
  #   command: bundle exec bin/webpack-dev-server --listen-host 0.0.0.0
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '3035:3035'
  #   depends_on:
  #     - db

volumes:
  db-data:
