allowBuilds:
  '@parcel/watcher': true
  core-js: true
  ejs: true
  esbuild: true
  fsevents: false
  styled-components: true
minimumReleaseAgeExclude:
  - '@posthog/core@1.30.9'
  - '@posthog/types@1.381.0'
  - posthog-js@1.381.0
