// flow-typed signature: 03981d2617ce2b6a3072e76f07320581
// flow-typed version: <<STUB>>/flow-inspect_v^1.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-inspect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-inspect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-inspect/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-inspect/bin.js' {
  declare module.exports: $Exports<'flow-inspect/bin'>;
}
declare module 'flow-inspect/index' {
  declare module.exports: $Exports<'flow-inspect'>;
}
declare module 'flow-inspect/index.js' {
  declare module.exports: $Exports<'flow-inspect'>;
}
