// flow-typed signature: 8dc488c3a27095ed1ca3c20ac83a1c94
// flow-typed version: <<STUB>>/react-google-analytics_v^0.2.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-analytics/gulpfile' {
  declare module.exports: any;
}

declare module 'react-google-analytics/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-analytics/gulpfile.js' {
  declare module.exports: $Exports<'react-google-analytics/gulpfile'>;
}
declare module 'react-google-analytics/lib/index.js' {
  declare module.exports: $Exports<'react-google-analytics/lib/index'>;
}
