// flow-typed signature: f7dc5420252aa0453be24f4b080eb6aa
// flow-typed version: <<STUB>>/react-youtube-player_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-youtube-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-youtube-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-youtube-player/dist/index' {
  declare module.exports: any;
}

declare module 'react-youtube-player/dist/stories/player' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-youtube-player/dist/index.js' {
  declare module.exports: $Exports<'react-youtube-player/dist/index'>;
}
declare module 'react-youtube-player/dist/stories/player.js' {
  declare module.exports: $Exports<'react-youtube-player/dist/stories/player'>;
}
