// flow-typed signature: 9caf3bf8f7ed0e737d4e2a5424745d9e
// flow-typed version: <<STUB>>/react-animate_v^3.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-animate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-animate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-animate/gulpfile' {
  declare module.exports: any;
}

declare module 'react-animate/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-animate/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-animate/gulpfile.js' {
  declare module.exports: $Exports<'react-animate/gulpfile'>;
}
declare module 'react-animate/src/__tests__/index.jsx' {
  declare module.exports: $Exports<'react-animate/src/__tests__/index'>;
}
declare module 'react-animate/src/index.jsx' {
  declare module.exports: $Exports<'react-animate/src/index'>;
}
