// flow-typed signature: 1b7ba6ca28b40235fd55ef73dcbf228c
// flow-typed version: <<STUB>>/react-youtube-player_v^0.3.3/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-youtube-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-youtube-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-youtube-player/dist/index' {
  declare module.exports: any;
}

declare module 'react-youtube-player/example/webpack.config' {
  declare module.exports: any;
}

declare module 'react-youtube-player/test/reactYoutubePlayer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-youtube-player/dist/index.js' {
  declare module.exports: $Exports<'react-youtube-player/dist/index'>;
}
declare module 'react-youtube-player/example/webpack.config.js' {
  declare module.exports: $Exports<'react-youtube-player/example/webpack.config'>;
}
declare module 'react-youtube-player/test/reactYoutubePlayer.js' {
  declare module.exports: $Exports<'react-youtube-player/test/reactYoutubePlayer'>;
}
