// flow-typed signature: a6f1dcb3231a0f45ed01687decd1c6bf
// flow-typed version: <<STUB>>/react-medium-image-zoom_v^0.8.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-medium-image-zoom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-medium-image-zoom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-medium-image-zoom/lib/react-medium-image-zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-medium-image-zoom/lib/react-medium-image-zoom.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/lib/react-medium-image-zoom'>;
}
