# frozen_string_literal: true

require 'rails_helper'

# Gala has no account-deletion workflow yet, and `Reader#destroy` is unsafe:
# it raises `ActiveRecord::InvalidForeignKey` for readers holding a `Lock` or a
# `CaseLibraryRequest`, and where it succeeds it leaves permanently-invalid
# comments and orphaned analytics behind. Both routes below are generated by
# gems rather than written by us, so they need explicit closing — and explicit
# tests, or a gem upgrade will quietly reopen them.
#
# Analysis in PR #796.
RSpec.describe 'Account deletion routes' do
  describe 'DELETE /readers' do
    it 'does not delete the signed-in reader' do
      reader = create(:reader)
      sign_in reader

      delete '/readers'

      expect(response).to have_http_status(:not_found)
      expect(Reader.find_by(id: reader.id)).to be_present
    end
  end

  describe 'DELETE /admin/readers/:id' do
    it 'does not delete the reader, even for an editor' do
      editor = create(:reader, :editor)
      target = create(:reader)
      sign_in editor

      delete "/admin/readers/#{target.id}"

      expect(response).to have_http_status(:not_found)
      expect(Reader.find_by(id: target.id)).to be_present
    end
  end

  it 'still routes sign-up, which shares the registrations controller' do
    get '/readers/sign_up'

    expect(response).to have_http_status(:success)
  end
end
