development:
  adapter: redis
  url: >
    <%= (ENV["REDIS_TEMPORARY_URL"] ||
    ENV["REDIS_URL"] ||
    "redis://localhost:6379/1").to_s.strip %>
  channel_prefix: orchard_development

test:
  adapter: async

production:
  adapter: redis
  url: >
    <%= (ENV["REDIS_TEMPORARY_URL"] ||
    ENV["REDIS_URL"] ||
    "redis://localhost:6379/1").to_s.strip %>
  channel_prefix: orchard_production
