---
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5).to_i %>
:timeout: 25
:verbose: true
:queues:
  - [critical, 1, { timeout: 10 }]
  - [high, 2, { timeout: 15 }]
  - [default, 3, { timeout: 25 }]
  - [mailers, 4, { timeout: 30 }]
  - [active_storage_analysis, 4, { timeout: 30 }]
  - [active_storage_purge, 4, { timeout: 30 }]
  - [ahoy, 5, { timeout: 30 }]